Implement '--clean' option for cleaning files
Added a new '--clean' option to clean injection files.

diff --git a/scripts/wrapper/termux/storm b/scripts/wrapper/termux/storm
--- a/scripts/wrapper/termux/storm
+++ b/scripts/wrapper/termux/storm
@@ -74,6 +74,15 @@ case "${1:-}" in
         fi
         ;;
 
+    --cleen)
+        if [ "$#" -eq 1 ]; then
+            python3 -m scripts.cleaning.clean
+        else
+            echo "[*] Invalid arguments: $*" >&2
+            exit 1
+        fi
+        ;;
+
     -h|--help)
         if [ "$#" -ne 1 ]; then
             echo "[*] Invalid arguments: $*" >&2
@@ -86,6 +95,7 @@ case "${1:-}" in
         echo "    [-v -L]          : Shows whether the latest update is available"
         echo "    [-c --crt]       : Copying CA to HOME Directory"
         echo "    [--update]       : Update to the latest version"
+        echo "    [--clean]        : Cleaning Injection files (If there are)"
         echo
         ;;
 
