Change data directory to config and update CA config
Updated directory navigation and CA generation configuration.

diff --git a/setuptermux b/setuptermux
--- a/setuptermux
+++ b/setuptermux
@@ -118,7 +118,7 @@ fi
 chmod 600 .env
 
 # Go to data folder
-cd "$INSTALL_DIR/data" || { echo -e "${RED}[x] ERROR: Lost track of directory!${NC}"; exit 1; }
+cd "$INSTALL_DIR/config" || { echo -e "${RED}[x] ERROR: Lost track of directory!${NC}"; exit 1; }
 
 # Generate ROOT CA TRUST STORE
 if [ -f smf_ca.key ] && [ -f smf_ca.crt ]; then
@@ -138,17 +138,7 @@ else
         -out smf_ca.crt \
         -subj "/CN=Storm Trusted Root CA/O=StormWorld0/OU=Network-Security-Storm" \
         -extensions v3_ca \
-        -config <(cat <<-EOF
-[req]
-distinguished_name = req_distinguished_name
-[req_distinguished_name]
-[v3_ca]
-subjectKeyIdentifier = hash
-authorityKeyIdentifier = keyid:always,issuer
-basicConstraints = critical, CA:true
-keyUsage = critical, digitalSignature, cRLSign, keyCertSign
-EOF
-        )
+        -config openssl-ca.conf
 
     echo "[✓] Success generate CA Trust Store"
 fi
