Fix invalid arguments error message output

diff --git a/scripts/wrapper/venv/storm b/scripts/wrapper/venv/storm
--- a/scripts/wrapper/venv/storm
+++ b/scripts/wrapper/venv/storm
@@ -55,7 +55,7 @@ case "${1:-}" in
 
     -c)
         if [ "${2:-}" != "--crt" ] || [ "$#" -ne 2 ]; then
-            echo "[*] Invalid arguments: $*"
+            echo "[*] Invalid arguments: $*" >&2
             exit 1
         fi
 
